language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq && sudo apt-get install -y gcc g++ gobjc llvm-dev; fi

script:
  - cd cctools && ./autogen.sh && ./configure && make
